{{- if .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "k8s-s3-sync.fullname" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-s3-sync.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
